# Generated by Django 2.1.1 on 2018-12-11 01:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20181211_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_master',
            name='number',
            field=models.CharField(help_text='number', max_length=7, validators=[django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
    ]
